### ISSUE TITLE
Report on using the most applicable BE API

### ISSUE THREAD

**Issue by winniepukki** [winniepukki/bonvoyage#11]
**Is your feature request related to a problem? Please describe.**
You were recently provided with the [Amadeus](https://developers.amadeus.com/self-service/category/covid-19-and-travel-safety/api-doc/travel-restrictions/api-reference) API as an example for requesting the data about the travel restrictions. You are now required to research information if we are able to use it, or provide alternatives.

**Describe the solution you'd like**
A clear and concise description of what API the app will use to operate with the Public restrictions queries

**Describe alternatives you've considered**
Please investigate alternatives, and is there a reason for purchasing any of those alternatives

**Additional context**
Make the report structured, fruitful and well-organized. Please ensure you are also up-to-date with the repository [Release flow](https://docs.reaktivelab.co/workflow/release-flow)

**Comment by ymarkoff** [comment]
**Describe the solution you'd like** The Travel Restrictions API provides up-to-date data on COVID-19 caseloads and travel restrictions for over 200 countries and territories, as well as hundreds of cities and regions worldwide. For a given country, city or region, the Travel Restrictions API will provide detailed data including:

- COVID-19 statistics - total cases, active cases, and current rate of infection per 100,000.  
- Travel restrictions - Flight and travel ban information, entry and exit requirements, and information on required tests, travel documents, and quarantines. 
- Local regulations - Information on hotspots, lockdowns, curfews and mask laws.

 
 **Describe alternatives you've considered** 

- TravelSafe API
- Sherpa API
- Smartvel API

I didn't go through with any of those as they only give demo access to existing companies.
