### ISSUE TITLE
Decide on the autocomplete ReactJS library

### ISSUE THREAD

**Issue by winniepukki** [winniepukki/bonvoyage#16]
**Is your feature request related to a problem? Please describe.**
The autocomplete library should be used to improve the UX during the country lookup process.

**Describe the solution you'd like**
- [ ] The library should provide a list of all possible countries
- [ ] The country list should include the flags
- [ ] The country list _**must not**_ include countries that are not supported by the API

**Describe alternatives you've considered**
The [MUI – Autocomplete](https://mui.com/components/autocomplete/) component provides the required auto-complete interface. It is important to investigate the need for using the library, instead of writing the custom module

**Additional context**
Any library implementation must be discussed prior to implementing the functionality

**Comment by ymarkoff** [comment]
**Is your feature request related to a problem? Please describe.**
https://mui.com/components/autocomplete/#country-select is the most optimal solution in terms of times and resources as it's working and using the material theme out of the box. We can also manipulate the country list quite easily, as they are not requested through an api, but set as a local data instead.


**Describe alternatives you've considered**
https://github.com/tlgadrkn/rest-countries-react is the second best choice, relying on calling the https://restcountries.com/ API for results. The main drawback compared to Mui is having to develop the ui to fit our app design.

https://www.npmjs.com/package/react-places-autocomplete I initially considered, but the Google Maps API is paid for and doesn't have a way to query countries.
