### ISSUE TITLE
Install bootstrap grid with media queries

### ISSUE THREAD

**Issue by winniepukki** [winniepukki/bonvoyage#32]
**Is your feature request related to a problem? Please describe.**
Bootstrap’s grid system uses a series of containers, rows, and columns to layout and align content. It’s built with [flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Using_CSS_flexible_boxes) and is fully responsive.

**Describe the solution you'd like**
The bootstrap grid must be used together with media queries as from [trinat](https://github.com/winniepukki/trinat/blob/main/src/app/style/abstract/_media.scss) project.

**Describe alternatives you've considered**
Not applicable.

**Additional context**
The latest bootstrap dependency must be installed.

**Comment by winniepukki** [comment]
@ymarkoff what is the ETA?

**Comment by ymarkoff** [comment]
This is sorted with PR #46 .
