### ISSUE TITLE
Error boundary component implementation

### ISSUE THREAD

**Issue by winniepukki** [winniepukki/bonvoyage#34]
**Is your feature request related to a problem? Please describe.**
When there is a runtime error during the development phase of your Next.js application, you will encounter an overlay. It is a modal that covers the webpage. It is only visible when the development server runs using `next dev`, `npm run dev`, or `yarn dev` and not in production. 

**Describe the solution you'd like**
React [Error Boundaries](https://reactjs.org/docs/error-boundaries.html) is a graceful way to handle a JavaScript error on the client so that the other parts of the application continue working. In addition to preventing the page from crashing, it allows you to provide a custom fallback component and even log error information.

**Describe alternatives you've considered**
The 404, and 500 pages should then be styled one day in the future. It's only the ErrorBoundary component for now.

**Additional context**
Please use the official [Next guide](https://nextjs.org/docs/advanced-features/error-handling) on implementing the ErrorBoundary component

**Comment by winniepukki** [comment]
@ymarkoff what is the ETA?

**Comment by ymarkoff** [comment]
@winniepukki This issue should be sorted with my latest pull request.
