### ISSUE TITLE
Next API routes for transferring the data from the COVID API's

### ISSUE THREAD

**Issue by winniepukki** [winniepukki/bonvoyage#35]
**Is your feature request related to a problem? Please describe.**
API routes provide a solution to [build your API with Next.js](https://nextjs.org/docs/api-routes/introduction). It is important for us to understand if it is a good practice to handle the calls to COVID-19 API's within the NextJS API routes and then forward information to components.

**Describe the solution you'd like**
It is essential for us to understand if we can use NextJS API routes for calling the COVID-19 API's and then forward the data in a REST format (or alike). This approach might prevent from developing the Back end API, if applicable. If is also important to understand if there is a need for that, since there is no need in using the NextJS API routes if the JavaScript fetch API can handle them.

**Describe alternatives you've considered**
The JavaScript fetch API

**Additional context**
Not applicable.

**Comment by ymarkoff** [comment]
We can indeed use the NextJS API routes to proxy requests to the COVID-19 API, but there isn't a real need for such verbosity in the context of this project, that I can see. It should be completely fine to make direct calls to the COVID-19 API.
