### ISSUE TITLE
Project Initiation Document draft environment description

### ISSUE THREAD

**Issue by winniepukki** [winniepukki/bonvoyage#68]
**Is your feature request related to a problem? Please describe.**
The project deliverables include the Project Initiation Document (PID) that describes the environment and other useful information.

**Describe the solution you'd like**
You should prepare the following information within a 1000-1500 word count: 

1. **_Project Summary & Introduction_**:  Provide a summary of the project purpose, background and context
2. **_Project Objectives_**: This section identifies the key project objectives – what specifically will this project achieve?
3. **_Project Deliverables:_** Provide a complete list of the deliverables/products the project produced.
4. **_Requirements_**: Point by point statement of project requirements (based on research and the gathering of appropriate project requirements from sprint 1)
5. **_Results_**: Presentation of results of testing, feedback and a valuation
6. **_Conclusions and Recommendation_**: Summary and presentation of the final product/artefact/solution and recommendations for any further work.

**Describe alternatives you've considered**
Not applicable.

**Additional context**
Other PID information shall be delivered by another developer. Please submit your information in a Word document with minimal text formatting, since the template has already been developed.

**Comment by winniepukki** [comment]
@ymarkoff please update on the task. Is there any progress?

**Comment by ymarkoff** [comment]
> @ymarkoff please update on the task. Is there any progress?

To complete the report on a meaningful note I need to know that my other PRs, else I have some stuff for the report that will be false.
